satoshis:
  # Tax rate in percent
  tax: 5.0
  # Whether or not the buyer will pay the extra tax
  is-buyer-responsible: true
  # Username of the owner (All taxes go to this player)
  owner: meta1203
  # Decimal place of Bitcoin (2-8)
  multiplier: 4.0
bitcoin:
  # Where to store all Bitcoin info
  wallet-file: 'plugins/Satoshis/wallet.wallet'
  # How long is a purchase request valid for?
  valid-for: 60
