satoshis:
  # Tax rate in percent
  tax: 5.0
  # Whether or not the buyer will pay the extra tax
  is-buyer-responsible: true
  # Username of the owner (All taxes go to this player)
  owner: meta1203
  # Value of single Bitcoin
  multiplier: 4.0
  # Name of the in-game currency
  currency-name: 'MTC'
bitcoin:
  # Use fees for withdrawls?
  fees: false
  # Transaction Confirmations required for insert of funding?
  confirms: 2
  # How often (in seconds) to check for pending confirmations?
  check-interval: 60
self-check:
  # How often to do a total system check? (Hours or -1 to disable)
  delay: -1
  # Do a total system check on startup?
  startup: false

