satoshis:
  # Tax rate in percent
  tax: 5.0
  # Whether or not the buyer will pay the extra tax
  is-buyer-responsible: true
  # Username of the owner (All taxes go to this player)
  owner: meta1203
  # Value of single Bitcoin
  multiplier: 4.0
bitcoin:
  # Where to store all Bitcoin info
  wallet-file: 'plugins/Satoshis/wallet.wallet'
  # How long is a purchase request valid for?
  valid-for: 60
  # Transaction Confirmations required for insert of funding?
  confirms: 2
  # How often (in seconds) to check for pending confirmations?
  check-interval: 60