satoshis:
  # Tax rate in percent
  tax: 5.0
  # Tax sales or withdrawals?
  sales-tax: true
  # Whether or not the buyer will pay the sales tax (only used if 'sales-tax' is enabled)
  is-buyer-responsible: true
  # Username of the owner (All taxes go to this player)
  owner: meta1203
  # Value of single Bitcoin
  multiplier: 4.0
  # Name of the in-game currency
  currency-name: 'MTC'
bitcoin:
  # Use fees for withdrawls? (recommended for small servers until a consistant flow of BTC is established)
  fees: true
  # Transaction Confirmations required for crediting player?
  confirms: 2
  # How often (in seconds) to check for pending confirmations?
  check-interval: 60
self-check:
  # How often to do a total system check? (Hours or -1 to disable)
  delay: -1
  # Do a total system check on startup?
  startup: false

