satoshis:
  # Tax rate in percent
  tax: 5.0
  # Whether or not the buyer will pay the extra tax
  is-buyer-responsible: true
  # Username of the owner (All taxes go to this player)
  owner: meta1203
  # Decimal place of Bitcoin (2-8)
  multiplier: 4.0
bitcoind:
  # Addresses of your bitcoin wallet (5+ recommended)
  addresses:
  - 1GgoXyKCMUr8VfbSmKRKiXjst7uCCarE8r
  - 1GgoXyKCMUr8VfbSmKRKiXjst7uCCarE8r
  - 1GgoXyKCMUr8VfbSmKRKiXjst7uCCarE8r
  - 1GgoXyKCMUr8VfbSmKRKiXjst7uCCarE8r
  - 1GgoXyKCMUr8VfbSmKRKiXjst7uCCarE8r
  # IP of bitcoind
  ip: 127.0.0.1
  # Port of bitcoind
  port: 8332
  # Username of bitcoind
  username: user
  # Password of bitcoind
  password: pass
