author: meta1203
database: true
main: me.meta1203.plugins.satoshis.Satoshis
name: Satoshis
url: http://www.metaserve.net/
softdepend: [Vault]
load: startup
version: '0.4'
commands:
  deposit:
    description: 'Deposit money through Bitcoin address'
  money:
    description: 'List money in possession'
  withdraw:
    description: 'Withdraw money into Bitcoin address'
  transact:
    description: 'Send in-game money to player'
  admin:
    description: 'Print testing info'
  syscheck:
    description: 'Check Satoshis system health'
permissions:
  satoshis.admin:
    description: 'Permission for Satoshis /admin'
  satoshis.withdraw:
    description: 'Permission for Satoshis /withdraw'
  satoshis.deposit:
    description: 'Permission for Satoshis /deposit'
  satoshis.transact:
    description: 'Permission for Satoshis /transact'
  satoshis.money:
    description: 'Permission for Satoshis /money'
  satoshis.info:
    description: 'Permission for Satoshis /syscheck'
